# Generated by Django 3.1 on 2020-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveBigIntegerField(unique=True, verbose_name="ID of user's telegram")),
                ('name', models.TextField(verbose_name="nickname of user's telegram")),
                ('invite_from', models.TextField(verbose_name='invite_from')),
                ('invited_users', models.PositiveIntegerField(verbose_name='invited_users')),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
    ]
